### ISSUE TITLE
Doesn't work on newest asf 

### ISSUE THREAD

**Issue by Zexxx** [Vital7/FriendAccepter#45]
Running on ubuntu i am getting this error
`2021-10-25 10:48:52|ArchiSteamFarm-3777675|ERROR|ASF|InitPlugins() System.MissingMethodException: Method not found: 'System.String System.Reflection.AssemblyMetadataAttribute.get_Value()'.
   at FriendAccepter.FriendAccepterPlugin.OnLoaded()
   at ArchiSteamFarm.Plugins.PluginsCore.InitPlugins()
`

**Comment by Vital7** [comment]
Hello, can you please attach full log.txt file? Probably you are running non-generic version, which might restrict from running this plugin.

**Comment by Zexxx** [comment]
[logs.txt](https://github.com/Vital7/FriendAccepter/files/7516473/logs.txt)
I'm pretty sure im running generic. 
Excuse the connection errors steam community was down at this time

**Comment by Vital7** [comment]
You're running linux-x64 version, however I am pretty sure this bug can be solved without switching to generic version
I'll keep you updated as I fix it 👍
